### ISSUE TITLE
Facebook connect endpoint

### ISSUE THREAD

**Issue by jwietelmann** [big-neon/bn-api-node#322]
connects to big-neon/bigneon#40
## What the request should require

* token - The Facebook API auth token
* expires - When it expires

## Other things we can send if you want them

* authorized permissions
* requested but denied permissions

## What I want to happen

* User is created if user does not exist
* User's FB info updated in Big Neon
* Respond with user info and Big Neon API auth token

**Comment by jwietelmann** [comment]
Cross-referencing my comment here for your convenience: https://github.com/revelrylabs/bn-mobile-react/issues/150#issuecomment-473310681

**Comment by Krakaw** [comment]
Thanks, will investigate

**Comment by Krakaw** [comment]
Closing, the fields that were not required are no longer required.
