### ISSUE TITLE
Transfers - A user should be able to cancel a ticket transfer they created until the transfer is accepted 

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api-node#345]
connected to big-neon/bigneon#145

Blocked by: big-neon/bn-api/issues/1260

Changes:
- Endpoint for cancelling ticket transfer support

**Comment by Anziskavds** [comment]
Reviewed and a user can cancel a transfer they created before it is accepted by the other user

**Comment by Timo614** [comment]
> Reviewed on Beta and a user can cancel a transfer they created before it is accepted by the other user

@Anziskavds did you mean something else above? The user should be able to cancel transfers before they are accepted. If they are accepted they can't be cancelled.

**Comment by Anziskavds** [comment]
Tested on Prod and it's working as expected on web and mobile web
